name: Continuous Integration
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  exercises:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercises
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Packages
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.9.0
          echo "$HOME/.deno/bin" >> "$GITHUB_PATH"
      - name: Tests
        run: deno test
      - name: Linting
        run: deno lint --unstable
      - name: Formatting
        run: deno fmt --check
