name: JavaScript Exercises
on:
  push:
    paths:
      - "javascript/exercises/**"
jobs:
  javascript-exercises:
    name: JavaScript Exercises
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript/exercises
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install JavaScript toolchain
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.12.0
          echo "$HOME/.deno/bin" >> "$GITHUB_PATH"
      - name: Run JavaScript tests
        run: deno test
      - name: Run JavaScript linter
        run: deno lint
